language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice
before_script:
  - psql -c 'create database tribunals_test;' -U postgres
services: postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
notifications:
  hipchat:
    rooms:
      secure: HxNbVehJdrap+dZ3vn1WJ5n1YoSezdLOjMKkBBOw9h4Zs6uCq+X8phEYYPIiGhalcu/V8FNTOAWAFLTwHN6YgTUn2Qh3Put5ZgEz0zGTJfmtpp7vI/bcHWPkoNEgaLHCH12YJ5N/DOuPIeDDdN90tAOjZqob/mfDCNUAQbgbAgY=
    format: html
    template:
      - '%{message} (<a href="%{build_url}">details</a>/<a href="%{compare_url}">changes</a>) - build #%{build_number}, branch <a href="https://github.com/%{repository}/tree/%{branch}">%{branch}</a>; of %{repository}'
